# Generated by Django 5.0.7 on 2024-07-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIRest', '0003_customers_customer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers_customer',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customers_customer',
            name='external_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='customers_customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loans_loan',
            name='external_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='payments_payment',
            name='external_id',
            field=models.CharField(max_length=40),
        ),
    ]
