# Generated by Django 5.0.7 on 2024-07-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIRest', '0004_alter_customers_customer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers_customer',
            name='preapproved_at',
            field=models.DateTimeField(),
        ),
    ]
