# Generated by Django 5.0.7 on 2024-07-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIRest', '0005_alter_customers_customer_preapproved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers_customer',
            name='external_id',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
