# Generated by Django 5.0.7 on 2024-07-27 02:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIRest', '0006_alter_customers_customer_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans_loan',
            name='external_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('11a8673d-1243-4f86-b479-f2a551356539'), null=True, unique=True),
        ),
    ]
