# Generated by Django 5.0.7 on 2024-07-27 03:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIRest', '0009_alter_loans_loan_contract_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans_loan',
            name='external_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('16bdc191-4bcc-11ef-9f57-080027053371'), null=True, unique=True),
        ),
    ]
