# Generated by Django 5.0.7 on 2024-07-27 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIRest', '0010_alter_loans_loan_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers_customer',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='loans_loan',
            name='external_id',
            field=models.CharField(default='c1', max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loans_loan',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='payments_payment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payments_payment',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIRest.customers_customer'),
        ),
        migrations.AlterField(
            model_name='payments_payment',
            name='external_id',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='payments_payment',
            name='paid_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payments_payment',
            name='status',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payments_payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payments_paymentdetail',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payments_paymentdetail',
            name='loan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIRest.loans_loan'),
        ),
        migrations.AlterField(
            model_name='payments_paymentdetail',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIRest.payments_payment'),
        ),
        migrations.AlterField(
            model_name='payments_paymentdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
