# Generated by Django 5.0.7 on 2024-07-28 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIRest', '0013_alter_loans_loan_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans_loan',
            name='contract_version',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='loans_loan',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='APIRest.customers_customer'),
        ),
    ]
