# Generated by Django 5.0.7 on 2024-07-29 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIRest', '0014_alter_loans_loan_contract_version_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers_customer',
            options={'ordering': ['created_at'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.RemoveField(
            model_name='loans_loan',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='loans_loan',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='APIRest.customers_customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers_customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customers_customer',
            name='preapproved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customers_customer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
        migrations.AlterField(
            model_name='loans_loan',
            name='contract_version',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='loans_loan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loans_loan',
            name='maximun_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loans_loan',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Active'), (3, 'Rejected'), (4, 'Paid')], default=2),
        ),
        migrations.AlterField(
            model_name='payments_payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payments_payment',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='APIRest.customers_customer'),
        ),
        migrations.AlterField(
            model_name='payments_payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payments_payment',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Completed'), (2, 'Rejected')], null=True),
        ),
        migrations.AlterField(
            model_name='payments_paymentdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payments_paymentdetail',
            name='loan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_payment', to='APIRest.loans_loan'),
        ),
        migrations.AlterField(
            model_name='payments_paymentdetail',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentdetail', to='APIRest.payments_payment'),
        ),
    ]
