# Generated by Django 5.0.7 on 2024-07-29 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIRest', '0015_alter_customers_customer_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loans_loan',
            old_name='customer',
            new_name='customer_id',
        ),
    ]
