# Generated by Django 5.0.7 on 2024-07-29 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIRest', '0016_rename_customer_loans_loan_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans_loan',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_set', to='APIRest.customers_customer'),
        ),
        migrations.AlterField(
            model_name='payments_payment',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_set', to='APIRest.customers_customer'),
        ),
        migrations.AlterField(
            model_name='payments_paymentdetail',
            name='loan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_loan_set', to='APIRest.loans_loan'),
        ),
        migrations.AlterField(
            model_name='payments_paymentdetail',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_set', to='APIRest.payments_payment'),
        ),
    ]
