# Generated by Django 5.0.7 on 2024-07-29 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIRest', '0018_alter_payments_paymentdetail_loan_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans_loan',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='APIRest.customers_customer'),
        ),
        migrations.AlterField(
            model_name='payments_payment',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='APIRest.customers_customer'),
        ),
    ]
